name = "TORBEAM"
uuid = "b9bf819a-2a49-451a-b482-4ce9066e62e1"
authors = ["Severin Denk <denks@fusion.gat.com>"]
version = "0.1.0"

[deps]
IMAS = "13ead8c1-b7d1-41bb-a6d0-5b8b65ed587a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
IMAS = "3.1.1"
Interpolations = "0.15.1"
Plots = "1.40.9"
