name = "TORBEAM"
uuid = "b9bf819a-2a49-451a-b482-4ce9066e62e1"
authors = ["Severin Denk <denks@fusion.gat.com>"]
version = "0.1.0"

[deps]
IMAS = "13ead8c1-b7d1-41bb-a6d0-5b8b65ed587a"

[extensions]
TORBEAMext = "Plots"

[compat]
IMAS = "3.4"
julia = "1"
